openapi: "3.0.0"
paths:
  /music:
    get:
      summary: List all songs
      operationId: listSongs
      tags:
        - songs
      parameters:
        - id: limit
          title:
          artist:
          gener:
          length:
          price:
          ...
      responses:
        ...
    post:
      summary: Create a song
      operationId: createSongs
      ...
  /music/{songId}:
    get:
      summary: Info for a specific song by id 
      operationId: showSongById
      ...
components:
  schemas:
    Songs:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
            unique:true

        title:
          type: string
        artist:
          type:string

        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string